# Generated by Django 5.1.1 on 2024-09-07 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Airlines',
                'db_table': 'airport.Airlines',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'airport.Discount',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_info', models.CharField(max_length=12, unique=True)),
                ('passport_details', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'airport.Passenger',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=10)),
                ('report_period', models.TextField()),
                ('creation_date', models.DateField()),
                ('creation_time', models.TimeField()),
                ('report_content', models.TextField()),
            ],
            options={
                'db_table': 'airport.Report',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'db_table': 'airport.Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('password_hash', models.CharField(max_length=14, unique=True)),
                ('salt', models.CharField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('middle_name', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_date', models.DateField()),
                ('last_date_of_authorization', models.DateField(blank=True, null=True)),
                ('last_date_of_deauthorization', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'airport.User',
            },
        ),
        migrations.CreateModel(
            name='ArrivalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField(unique=True)),
                ('flight_number', models.CharField(max_length=4)),
                ('departure_location', models.CharField(max_length=20)),
                ('transport_model', models.CharField(max_length=15)),
                ('days_week', models.DateField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.airlines')),
            ],
            options={
                'db_table': 'airport.ArrivalSchedule',
            },
        ),
        migrations.CreateModel(
            name='DepartureSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=4)),
                ('route', models.CharField(max_length=15)),
                ('departure_date', models.DateField()),
                ('departure_time', models.DateTimeField(unique=True)),
                ('transport_model', models.CharField(max_length=15)),
                ('days_week', models.DateField(blank=True, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.airlines')),
            ],
            options={
                'db_table': 'airport.DepartureSchedule',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('transport_type', models.CharField(max_length=8)),
                ('transport_model', models.CharField(max_length=15)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField(unique=True)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField(unique=True)),
                ('departure_location', models.CharField(max_length=20)),
                ('arrival_location', models.CharField(max_length=20)),
                ('flight_status', models.CharField(max_length=10)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.airlines')),
            ],
            options={
                'db_table': 'airport.Flight',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField()),
                ('send_time', models.TimeField()),
                ('notification_text', models.TextField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.passenger')),
            ],
            options={
                'db_table': 'airport.Notification',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number_of_ticket', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ticket_category', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.discount')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.passenger')),
            ],
            options={
                'db_table': 'airport.Ticket',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
            options={
                'db_table': 'airport.UserRole',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_revocation', models.DateField()),
                ('reviews', models.TextField()),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.passenger')),
            ],
            options={
                'db_table': 'airport.Reviews',
                'unique_together': {('date_of_revocation', 'passenger', 'reviews')},
            },
        ),
    ]
