# Generated by Django 5.1.1 on 2024-09-08 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date_of_revocation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
