# Generated by Django 5.1.1 on 2024-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_reviews_photo_alter_reviews_date_of_revocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='reviews',
            new_name='review_text',
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('date_of_revocation', 'passenger', 'review_text')},
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(default='Аноним', max_length=100),
        ),
    ]
