# Generated by Django 5.1.1 on 2024-09-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_reviews_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
    ]
