# Generated by Django 5.1.1 on 2024-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_ticket_category_remove_ticket_ticket_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departureschedule',
            name='flight_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
